name: Run test and deploy
on: push

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest test_lib.py
  deploy:
    needs: run-tests
    runs-on: ubuntu-22.04
    steps:
        - name: Deploy Flask app
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            port: 22
            script: |
              ~/deploy.sh